apiVersion: v1
kind: Config
preferences: {}

clusters:
- name: gaia-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXprNU16VTJNakV3SGhjTk1qVXdNakU1TURNeU56QXhXaGNOTXpVd01qRTNNRE15TnpBeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXprNU16VTJNakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWE4yOXNuaWdoMHEwSVBMQWVlU2RSd0dXbllpQmFERGJTdEpKQ0s2Z2cKaDVaeDhvL0YvclZMMi9iNklTYUdkMmJBamRxUkRCdllQdWlUQzRTRC9lTUZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdqRDRBY0ZrVTBGUGp5bFNoYzE4CkVwY3pTVkF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTk9JY0JjMGdERkZ0Vnp5bG9CWnJMdTFrbXp6MzJoMVgKY2VBY3BsUWlKSjRDSUI4OGRXZ0RtSG5LUVREdWVaY1JuaFZPcTdoMENTUHdSUzJ0L1IwM3RBalUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://172.16.1.1:6443

users:
- name: ras-member
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjM0TURrSUFJOXl1LVlXVlE3TFlCQ2RMRklBaE51UE50LS1vRXNaVWtGYm8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkb2NrZXItd29ya3Nob3AiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmFzLW1lbWJlci10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJyYXMtbWVtYmVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMjlhNDNlNjQtMzM0Yy00MjJhLTg1OTAtNjA4MDQzNjQxMjdlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRvY2tlci13b3Jrc2hvcDpyYXMtbWVtYmVyIn0.viMH7ZrlzSKmOwKOr8p-w9YSWSMjlgH8v4Ff2uhfedftyfTthVKVEehhpLemGcDqlij306a_-sRK1afTXX2oZs-t6xX4dGwXPuy4mDzvN9P9J8AJ5HZzZNUvIBahC2Z7PZUR9bxm8yvXxOMuLmhu8yxAhsWLrMF-65U-GmIf3Jg0U0SAzF-01xrSYUF3N8T6nWcJx_w0EThP5WMcCRFs6pVcP9yzmcpclmz1q-50mYrIx1sRcp5bZTFwCmcbRezXoqqjTAFE9PKrxjD9aQIXzpA6l-d-JO9ds0AmYbco2y8HY9ZX1w2zLbM-gGZPfjKKmxwDaaRSynh9TffhNux57w

contexts:
- name: ras-member-docker-workshop
  context:
    cluster: gaia-cluster
    user: ras-member
    namespace: docker-workshop

current-context: ras-member-docker-workshop
