apiVersion: v1
kind: Config
preferences: {}

clusters:
- name: gaia-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXprNU16VTJNakV3SGhjTk1qVXdNakU1TURNeU56QXhXaGNOTXpVd01qRTNNRE15TnpBeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXprNU16VTJNakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWE4yOXNuaWdoMHEwSVBMQWVlU2RSd0dXbllpQmFERGJTdEpKQ0s2Z2cKaDVaeDhvL0YvclZMMi9iNklTYUdkMmJBamRxUkRCdllQdWlUQzRTRC9lTUZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdqRDRBY0ZrVTBGUGp5bFNoYzE4CkVwY3pTVkF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTk9JY0JjMGdERkZ0Vnp5bG9CWnJMdTFrbXp6MzJoMVgKY2VBY3BsUWlKSjRDSUI4OGRXZ0RtSG5LUVREdWVaY1JuaFZPcTdoMENTUHdSUzJ0L1IwM3RBalUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://172.16.1.1:6443

users:
- name: ras-member
  user:
    as-user-extra: {}
    token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqTTBUVVJyU1VGSk9YbDFMVmxYVmxFM1RGbENRMlJNUmtsQmFFNTFVRTUwTFMxdlJYTmFWV3RHWW04aWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprYjJOclpYSXRkMjl5YTNOb2IzQWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObFkzSmxkQzV1WVcxbElqb2ljbUZ6TFcxbGJXSmxjaTEwYjJ0bGJpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSnlZWE10YldWdFltVnlJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1ZFdsa0lqb2lNamxoTkRObE5qUXRNek0wWXkwME1qSmhMVGcxT1RBdE5qQTRNRFF6TmpReE1qZGxJaXdpYzNWaUlqb2ljM2x6ZEdWdE9uTmxjblpwWTJWaFkyTnZkVzUwT21SdlkydGxjaTEzYjNKcmMyaHZjRHB5WVhNdGJXVnRZbVZ5SW4wLnZpTUg3WnJselNLbU93S09yOHAtdzlZU1dTTWpsZ0g4djRGZjJ1aGZlZGZ0eWZUdGhWS1ZFZWhocExlbUdjRHFsaWozMDZhXy1zUksxYWZUWFgyb1pzLXQ2eFg0ZEd3WFB1eTRtRHp2TjlQOUo4QUo1SFp6Wk5VdklCYWhDMlo3UFpVUjlieG04eXZYeE9NdUxtaHU4eXhBaHNXTHJNRi02NVUtR21JZjNKZzBVMFNBekYtMDF4clNZVUYzTjhUNm5XY0p4X3cwRVRoUDVXTWNDUkZzNnBWY1A5eXptY3BjbG16MXEtNTBtWXJJeDFzUmNwNWJaVEZ3Q21jYlJlelhvcXFqVEFGRTlQS3J4akQ5YVFJWHpwQTZsLWQtSk85ZHMwQW1ZYmNvMnk4SFk5WlgxdzJ6TGJNLWdHWlBmaktLbXh3RGFhUlN5bmg5VGZmaE51eDU3dw==

contexts:
- name: ras-member-docker-workshop
  context:
    cluster: gaia-cluster
    user: ras-member
    namespace: docker-workshop

current-context: ras-member-docker-workshop
