apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: docker-workshop
rules:
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - create
    - delete
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
      - list
      - watch
      - create
      - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - list
  - get
  - watch
